import { useState } from "react";
import { Bell, Building2, Database, Globe2, Lock, Palette, Play, RotateCcw, Save, ShieldCheck } from "lucide-react";
import { modeSchedule, themeOptions } from "../data/demoData";
import { useDemo } from "../state/DemoContext";
import { DataExplanation, InfoTip, SectionTitle } from "../components/Common";

export function StructurePage() {
  const { state, actions } = useDemo();
  return <div className="screen-enter"><SectionTitle eyebrow="STRUTTURA" title="Residenza Aurora" description="Configurazione operativa, modalità ROSS e fasce di quiete." action={<button className="primary-button"><Save size={16} /> Salva modifiche</button>} /><div className="settings-grid"><section className="surface settings-section"><header><span><Building2 /></span><div><h3>Informazioni generali</h3><p>Identità e impostazioni della struttura demo.</p></div></header><div className="form-grid"><label>Nome struttura<input defaultValue="Residenza Aurora" /></label><label>Timezone<select defaultValue="Europe/Rome"><option>Europe/Rome</option></select></label><label>Lingua<select defaultValue="Italiano"><option>Italiano</option><option>English</option></select></label><label>Ultimo aggiornamento<input value="2 min fa" readOnly /></label></div></section><section className="surface settings-section schedule-section"><header><span><Play /></span><div><h3>Programmazione modalità ROSS</h3><p>Definisce quando ROSS può proporre attività o resta in quiete.</p></div></header><div className="schedule-list">{state.schedule.map((item, index) => <div key={`${item.start}-${index}`}><input type="time" value={item.start} onChange={(e) => actions.updateSchedule(index, { start: e.target.value })} /><span>→</span><input type="time" value={item.end} onChange={(e) => actions.updateSchedule(index, { end: e.target.value })} /><select value={item.mode} onChange={(e) => actions.updateSchedule(index, { mode: e.target.value })}><option>Attiva</option><option>Reattiva</option><option>Silenziosa</option></select></div>)}</div><DataExplanation>In modalità Silenziosa ROSS non avvia interazioni e rispetta il momento di riposo.</DataExplanation></section><section className="surface settings-section"><header><span><Lock /></span><div><h3>Privacy e permessi</h3><p>Comunicazione trasparente del comportamento locale.</p></div></header>{[["Elaborazione locale", "Attiva"], ["Conservazione demo", "90 giorni"], ["Accesso operatori", "Solo autorizzati"], ["Esportazione", "Con tracciamento"]].map(([label, value]) => <div className="setting-row" key={label}><span>{label}<InfoTip label={label} text="Impostazione dimostrativa, non certificazione tecnica o normativa." /></span><strong>{value}</strong></div>)}</section><section className="surface settings-section"><header><span><Database /></span><div><h3>Stato demo</h3><p>Dataset locale, deterministico e ripristinabile.</p></div></header><div className="demo-status"><div><strong>{state.interactions.length}</strong><span>interazioni</span></div><div><strong>{state.memories.length}</strong><span>memorie</span></div><div><strong>{state.residents.length}</strong><span>ospiti</span></div></div><button className="danger-button" onClick={actions.reset}><RotateCcw size={16} /> Ripristina dataset demo</button></section></div></div>;
}

export function SettingsPage() {
  const { state, actions } = useDemo();
  const [saved, setSaved] = useState(false);
  return <div className="screen-enter"><SectionTitle eyebrow="PREFERENZE" title="Impostazioni" description="Aspetto, comportamento della demo e preferenze operatore." /><div className="settings-layout"><nav className="settings-nav"><button className="active"><Palette size={17} /> Tema</button><button><Bell size={17} /> Notifiche</button><button><ShieldCheck size={17} /> Privacy</button><button><Globe2 size={17} /> Lingua</button></nav><section className="settings-content surface"><span className="eyebrow">ASPETTO</span><h2>Scegli il tema</h2><p>Il cambio è istantaneo e include grafici, badge e stati.</p><div className="theme-cards">{themeOptions.map((theme) => <button key={theme.id} className={state.theme === theme.id ? "active" : ""} onClick={() => actions.setTheme(theme.id)}><div className={`theme-preview preview-${theme.id}`}><span /><span /><span /></div><strong>{theme.name}</strong><small>{theme.description}</small>{state.theme === theme.id && <span className="theme-selected">Selezionato</span>}</button>)}</div><hr /><h3>Modalità presentazione</h3><div className="setting-row"><div><strong>Percorso guidato</strong><p>Mostra le schermate principali nello stato ideale per un pitch.</p></div><label className="switch"><input type="checkbox" checked={state.presentation} onChange={actions.togglePresentation} /><span /></label></div><div className="setting-row"><div><strong>Schermate 16:9</strong><p>Disponibile anche aggiungendo <code>?presentation=true</code> all'indirizzo.</p></div><span>Automatico</span></div><button className="primary-button" onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 1800); }}><Save size={16} /> {saved ? "Salvato" : "Salva preferenze"}</button></section></div></div>;
}
